### ISSUE TITLE
Android and Ios: Need a way to refresh activity count

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/study-goals#11]
You can refresh attainment, but not activity.  So we need re to be able to refresh the activity count as well.

**Comment by TherapyBox** [comment]
Is it okay to make the entire page refreshable rather than having two separate refresh buttons on one relatively small page?

**Comment by michaelwebbjisc** [comment]
Yes, that would be fine

**Comment by michaelwebbjisc** [comment]
Thanks, tested and label for iOS removed

**Comment by TherapyBox** [comment]
We've made the same change on Android

**Comment by robwynj** [comment]
To be tested on Android - can you also validate please @michaelwebbjisc 

Many Thanks, Rob

**Comment by robwynj** [comment]
Update required @TherapyBox
