### ISSUE TITLE
Welsh Translations Missing

### ISSUE THREAD

**Issue by robwynj** [jiscdev/study-goals#16]
Some activity feed text are still in welsh - including:

Donna Powell has accepted your friend request
Donna Powell has added a new target for Revising for 45 minutes Daily
Rydych wedi ennill y tlws "Loudspeaker (Silver"!

Also seen the test (is this a user comment made, manually via the app):
Email search

Also, within Engagement Graphs -

the time period for "past 7 days" in welsh as "7A diwrnod dwethaf" - it should not be 7A - just 7!

To be resolved between @TherapyBox and @robwynj - @TherapyBox need to provide gaps missing to RWJ (Google Sheets) for updating

**Comment by robwynj** [comment]
FAO TB - can you confirm current status here.

Kind Regards, Rob

**Comment by mparker-tbox** [comment]
I believe these issues were resolved. Welsh should be up to date.

**Comment by mparker-tbox** [comment]
Hi, just rechecked. Welsh issues are still there. I will check with developer and have an update for you in tomorrow's call

**Comment by robwynj** [comment]
Thanks Matthew
