### ISSUE TITLE
IOS Engagement Graph is drawing back to front

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/study-goals#31]
e.g. for last 7 days:

API returns 0, -1, -2 etc to mean today, yesterday, 2 days ago
App draws the entry for 0 as 7 days ago, entry for -1 as 6 days ago, entry for -2 as 5 days ago, etc.

i.e. back-to-front.

Interpretation of -n is incorrect.

**Comment by TherapyBox** [comment]
Will change along with other graph fixes.
