### ISSUE TITLE
Double space between 'like' and 'to' on My Friends page

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goals#56]
![space between like to](https://cloud.githubusercontent.com/assets/5815497/20664078/ae3dd194-b551-11e6-9b28-27ee6174cf01.png)

**Comment by robwynj** [comment]
Re: email from @TherapyBox (Matthew) -> 

Welsh translation for the above english text (in full as "What would you like your friend to see?”):

"Be fysech yn hoffi eich ffrind i weld?"

Kind Regards

Rob

**Comment by robwynj** [comment]
Welsh version here FYI @TherapyBox - see attachment...

**Comment by robwynj** [comment]
[
![apperror1](https://cloud.githubusercontent.com/assets/16684142/20708661/f39a17a2-b628-11e6-8c45-a86bfbd8745e.png)
](url)

**Comment by mparker-tbox** [comment]
Changed, so that it reads "What would you like your friend to see?"
