### ISSUE TITLE
iOS Tab Bar Issue on iPad (sizing of highlight)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goals#57]
On iPhone the tab bar icons are sized correctly - see image below:
<img src="https://cloud.githubusercontent.com/assets/5815497/20668556/5c078b48-b567-11e6-83b8-c964970bb243.png" width="300">

On iPad the blue highlight box appears to be slightly too small - see image below:
<img src="https://cloud.githubusercontent.com/assets/5815497/20668586/7bef503a-b567-11e6-9dc2-c34e1d808db8.png" width="700">

I suggest we could just use the blue text colour to highlight the selected section. This would therefore solve the sizing issue on iPads - see example below:
<img src="https://cloud.githubusercontent.com/assets/5815497/20668611/908e62b0-b567-11e6-9157-c01279263c95.png" width="300">

**Comment by mparker-tbox** [comment]
Changed, but blue was difficult to read, so we've used Jisc orange instead.
