### ISSUE TITLE
Display message when there are no new friend requests

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goals#59]
On the New Requests tab within the Friends section it might be worth having a popup or label on the screen that informs the user there are no new requests. 

Reason: whenever I see a blank screen with no content I assume something has broken/failed to load. See image below:

<img src="https://cloud.githubusercontent.com/assets/5815497/20672376/044536b4-b579-11e6-9bcd-219e0e4b7006.png" width="300">

**Comment by robwynj** [comment]
Re: email from @TherapyBox (Matthew) ->

Welsh translation for the above english text (in full as ""You do not have any new friend requests at the moment."):

"Does dim ceisiadau ffrind newydd gyda chi ar y foment"

Kind Regards

Rob

**Comment by mparker-tbox** [comment]
Resolved. Sending version through shortly
